USE CSDL;
create table NHAN_HIEU (
 MA_NSX VARCHAR(10) PRIMARY KEY,
 TEN_NSX NVARCHAR(100) NOT NULL,
 NUOC NVARCHAR(100) NOT NULL,
);

CREATE TABLE LOAI_TB (
 MA_LOAI VARCHAR(10) PRIMARY KEY,
 TEN_LOAI NVARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE DON_VI(
 MA_DV VARCHAR(10) PRIMARY KEY,
 TEN_DV NVARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE PHONG(
 MA_PHONG VARCHAR(10) PRIMARY KEY,
 VI_TRI NVARCHAR(100) NOT NULL UNIQUE,
 DIEN_TICH FLOAT CHECK (DIEN_TICH > 0),
);

CREATE TABLE PHG_DV (
    MA_PHONG VARCHAR(10),
    MA_DV VARCHAR(10),
    NGAY_BD DATE NOT NULL,
    NGAY_KT DATE,

    PRIMARY KEY (MA_PHONG, MA_DV, NGAY_BD),
    CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

    FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (MA_DV) REFERENCES DON_VI(MA_DV)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE THIET_BI(
 MA_TB VARCHAR(10) PRIMARY KEY,
 TEN_TB NVARCHAR(50) NOT NULL,
 MA_NHHIEU VARCHAR(10) NOT NULL,
 MODEL NVARCHAR(50) NOT NULL,
 NAM_SX INT CHECK (NAM_SX > 2000),
 MA_LOAI VARCHAR(10) NOT NULL,
 FOREIGN KEY (MA_LOAI) REFERENCES LOAI_TB(MA_LOAI)
  ON UPDATE CASCADE
  ON DELETE NO ACTION
);

CREATE TABLE NV(
 MA_NV VARCHAR(10) PRIMARY KEY CHECK (MA_NV LIKE '[A-Z][1-9][0-9][0-9][0-9][0-9][0-9]'),
 HO_NV NVARCHAR(10) NOT NULL,
 TEN_NV NVARCHAR(50),
 PHAI NVARCHAR(10) NOT NULL CHECK (PHAI IN (N'Nam', N'Nữ', N'Khác')),
 NGAY_BD_CTAC DATE NOT NULL,
);

CREATE TABLE MON_TB(
 MA_MON VARCHAR(10) PRIMARY KEY,
 MA_TB VARCHAR(10) NOT NULL,
 NGAY_MUA DATE NOT NULL,
 TRI_GIA_MUA DECIMAL(16,2) CHECK (TRI_GIA_MUA > 0), 
 FOREIGN KEY (MA_TB) REFERENCES THIET_BI(MA_TB)
  ON UPDATE CASCADE
  ON DELETE NO ACTION
);

CREATE TABLE LDAO_CQ(
 MA_NV VARCHAR(10) NOT NULL,
 CHUC_VU NVARCHAR(50) NOT NULL,
 NGAY_BD DATE NOT NULL,
 NGAY_KT DATE,
 PRIMARY KEY (MA_NV, NGAY_BD),
 CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),
 FOREIGN KEY (MA_NV) REFERENCES NV(MA_NV)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);

CREATE TABLE LDAO_DV(
 MA_NV VARCHAR(10),
 MA_DV VARCHAR(10),
 CHUC_VU NVARCHAR(50) NOT NULL,
 NGAY_BD DATE NOT NULL,
 NGAY_KT DATE,

 PRIMARY KEY (MA_NV, MA_DV, NGAY_BD),
 CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

 FOREIGN KEY (MA_NV) REFERENCES NV(MA_NV)
 ON UPDATE CASCADE
 ON DELETE CASCADE,

 FOREIGN KEY (MA_DV) REFERENCES DON_VI(MA_DV)
 ON UPDATE CASCADE
 ON DELETE CASCADE
 );

 CREATE TABLE PHTRACH_TB(
 MA_NV VARCHAR(10),
 MA_DV VARCHAR(10),
 NGAY_BD DATE NOT NULL,
    NGAY_KT DATE,

 PRIMARY KEY (MA_NV, MA_DV, NGAY_BD),
    CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

 FOREIGN KEY (MA_NV) REFERENCES NV(MA_NV)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (MA_DV) REFERENCES DON_VI(MA_DV)
        ON UPDATE CASCADE
        ON DELETE CASCADE
 );

CREATE TABLE PH_PHOI_TB (
    MA_PHONG VARCHAR(10),
    MA_MON VARCHAR(10),
    NGAY_BD DATE NOT NULL,
    NGAY_KT DATE,
    MUC_TTRANG NVARCHAR(50)
	CHECK (MUC_TTRANG IN ('Tốt','Hỏng','Bảo trì','Thanh lý')),
    MO_TA_TTRANG VARCHAR(255),

    PRIMARY KEY (MA_PHONG, MA_MON, NGAY_BD),
    CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

    FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,

    FOREIGN KEY (MA_MON) REFERENCES MON_TB(MA_MON)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

ALTER TABLE PH_PHOI_TB DROP CONSTRAINT CK__PH_PHOI_T__MUC_T__4CA06362;

ALTER TABLE PH_PHOI_TB ADD CONSTRAINT CHK_MUC_TTRANG 
CHECK (MUC_TTRANG IN (N'Tốt', N'Hỏng', N'Bảo trì', N'Thanh lý'));

CREATE TABLE THANH_LY (
    MA_MON VARCHAR(10),
    NGAY_GIO DATETIME,
    TRI_GIA DECIMAL(15,2) NOT NULL CHECK (TRI_GIA > 0),
    DV_TIEN VARCHAR(10) NOT NULL,

    PRIMARY KEY (MA_MON, NGAY_GIO),

    FOREIGN KEY (MA_MON) REFERENCES MON_TB(MA_MON)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE KHAU_HAO (
    MA_MON VARCHAR(10),
    NGAY DATE,
    TY_LE_KH FLOAT NOT NULL CHECK (TY_LE_KH >= 0 AND TY_LE_KH <= 1),

    PRIMARY KEY (MA_MON, NGAY),

    FOREIGN KEY (MA_MON) REFERENCES MON_TB(MA_MON)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


--cau 8
SELECT TB.TEN_TB, L.TEN_LOAI, NH.TEN_NSX, TB.MODEL, TB.NAM_SX
FROM PH_PHOI_TB PP, MON_TB MT, THIET_BI TB, LOAI_TB L, NHAN_HIEU NH
WHERE PP.MA_MON = MT.MA_MON
  AND MT.MA_TB = TB.MA_TB
  AND TB.MA_LOAI = L.MA_LOAI
  AND TB.MA_NHHIEU = NH.MA_NSX
  AND PP.NGAY_KT IS NOT NULL
  AND DATEDIFF(DAY, PP.NGAY_BD, PP.NGAY_KT) = (
      SELECT MAX(DATEDIFF(DAY, NGAY_BD, NGAY_KT))
      FROM PH_PHOI_TB
      WHERE NGAY_KT IS NOT NULL
  );

  --cau 9
SELECT SUM(TRI_GIA) AS TONG_TRI_GIA
FROM THANH_LY
WHERE NGAY_GIO >= '2007-11-01' 
  AND NGAY_GIO < '2008-01-01';

--cau 10
SELECT TB.MODEL, TB.TEN_TB
FROM THIET_BI TB, MON_TB MT, PH_PHOI_TB PP, PHG_DV PD, DON_VI DV, KHAU_HAO KH
WHERE TB.MA_TB = MT.MA_TB
  AND MT.MA_MON = PP.MA_MON
  AND PP.MA_PHONG = PD.MA_PHONG
  AND PD.MA_DV = DV.MA_DV
  AND MT.MA_MON = KH.MA_MON
  AND DV.TEN_DV = N'Phòng Nghiên cứu và Phát triển' 
  AND KH.NGAY >= DATEADD(YEAR, 1, MT.NGAY_MUA)
GROUP BY TB.MODEL, TB.TEN_TB, MT.MA_MON
HAVING AVG(KH.TY_LE_KH) > 0.9;

use CSDL
GO

-- 1. NHÃN HIỆU (Chuẩn bị cho Câu 1, Câu 2, Câu 7)
INSERT INTO NHAN_HIEU (MA_NSX, TEN_NSX, NUOC) VALUES
('NH01', N'Panasonic', N'Nhật Bản'),
('NH02', N'Á châu', N'Việt Nam'),
('NH03', N'Sony', N'Nhật Bản'),
('NH04', N'Dell', N'Mỹ');

-- 2. LOẠI THIẾT BỊ
INSERT INTO LOAI_TB (MA_LOAI, TEN_LOAI) VALUES
('L01', N'Máy chiếu'),
('L02', N'Quạt làm mát'),
('L03', N'Máy tính'),
('L04', N'Máy lạnh');

-- 3. THIẾT BỊ (Chuẩn bị Quạt trần Á châu AC50 cho Câu 7, Panasonic cho Câu 1)
INSERT INTO THIET_BI (MA_TB, TEN_TB, MA_NHHIEU, MODEL, NAM_SX, MA_LOAI) VALUES
('TB01', N'Máy chiếu cường độ cao', 'NH01', 'PX-100', 2020, 'L01'),
('TB02', N'Quạt trần', 'NH02', 'AC50', 2005, 'L02'), 
('TB03', N'Máy lạnh Inverter', 'NH01', 'PN-200', 2021, 'L04'),
('TB04', N'Laptop đồ họa', 'NH04', 'XPS-15', 2022, 'L03');

-- 4. ĐƠN VỊ & PHÒNG (Chuẩn bị Phòng Kế Toán cho Câu 5, Nghiên cứu & PT cho Câu 10)
INSERT INTO DON_VI (MA_DV, TEN_DV) VALUES
('DV01', N'Phòng Kế Toán'),
('DV02', N'Phòng Nghiên cứu và Phát triển'),
('DV03', N'Phòng Hành Chính');

INSERT INTO PHONG (MA_PHONG, VI_TRI, DIEN_TICH) VALUES
('P01', N'Phòng 101 Tầng 1', 50.5),
('P02', N'Phòng 201 Tầng 2', 80.0),
('P03', N'Phòng 102 Tầng 1', 45.0);

INSERT INTO PHG_DV (MA_PHONG, MA_DV, NGAY_BD, NGAY_KT) VALUES
('P01', 'DV01', '2015-01-01', NULL),
('P02', 'DV02', '2015-01-01', NULL),
('P03', 'DV03', '2015-01-01', NULL);

-- 5. NHÂN VIÊN (Chuẩn bị Lê Văn Tân và Trần Thanh Nhã cho Câu 5, Câu 6)
-- Lưu ý: Định dạng MA_NV là 1 chữ in hoa + 6 số (VD: A123456)
INSERT INTO NV (MA_NV, HO_NV, TEN_NV, PHAI, NGAY_BD_CTAC) VALUES
('A123456', N'Lê', N'Văn Tân', N'Nam', '2010-05-01'),
('B234567', N'Trần', N'Thanh Nhã', N'Nữ', '2012-08-15'),
('C345678', N'Nguyễn', N'Thị Cẩm', N'Nữ', '2018-02-01'),
('D456789', N'Phạm', N'Hùng', N'Nam', '2015-10-10');

-- 6. LÃNH ĐẠO CƠ QUAN & ĐƠN VỊ (Trần Thanh Nhã làm GĐ, Lê Văn Tân lãnh đạo Kế Toán)
INSERT INTO LDAO_CQ (MA_NV, CHUC_VU, NGAY_BD, NGAY_KT) VALUES
('B234567', N'Giám đốc', '2020-01-01', NULL);

INSERT INTO LDAO_DV (MA_NV, MA_DV, CHUC_VU, NGAY_BD, NGAY_KT) VALUES
('A123456', 'DV01', N'Trưởng phòng', '2018-01-01', NULL),
('D456789', 'DV02', N'Trưởng phòng', '2019-01-01', NULL);

-- 7. PHỤ TRÁCH THIẾT BỊ (Cán bộ phụ trách Kế Toán lúc Lê Văn Tân làm TP cho Câu 5)
INSERT INTO PHTRACH_TB (MA_NV, MA_DV, NGAY_BD, NGAY_KT) VALUES
('C345678', 'DV01', '2019-06-01', NULL);

-- 8. MÓN THIẾT BỊ (Ngày mua phải khớp thời gian lãnh đạo để đếm số món/kinh phí)
INSERT INTO MON_TB (MA_MON, MA_TB, NGAY_MUA, TRI_GIA_MUA) VALUES
('M01', 'TB01', '2021-03-15', 15000000), -- Thuộc nhiệm kỳ GĐ Nhã, TP Tân
('M02', 'TB01', '2021-04-20', 15000000), -- Thuộc nhiệm kỳ GĐ Nhã, TP Tân
('M03', 'TB02', '2006-12-10', 800000),   -- Quạt trần Á Châu mua năm 2006 (Dùng lâu nhất cho Câu 8)
('M04', 'TB03', '2022-05-10', 12000000), 
('M05', 'TB04', '2020-08-25', 35000000); 

-- 9. PHÂN PHỐI THIẾT BỊ (Phân phối về các phòng để tính khấu hao và thanh lý)

INSERT INTO PH_PHOI_TB (MA_PHONG, MA_MON, NGAY_BD, NGAY_KT, MUC_TTRANG, MO_TA_TTRANG) VALUES
('P01', 'M01', '2021-03-20', '2023-01-20', N'Tốt', N'Sử dụng bình thường'),
('P01', 'M02', '2021-04-25', NULL, N'Tốt', N'Sử dụng bình thường'),
('P03', 'M03', '2007-01-05', '2010-01-05', N'Tốt', N'Đang chạy'),
('P02', 'M04', '2022-05-15', NULL, N'Tốt', N'Sử dụng bình thường'),
('P02', 'M05', '2020-09-01', NULL, N'Tốt', N'Sử dụng bình thường');

INSERT INTO PH_PHOI_TB (MA_PHONG, MA_MON, NGAY_BD, NGAY_KT, MUC_TTRANG, MO_TA_TTRANG) VALUES
('P01', 'M01', '2021-03-20', '2023-01-20', N'Tốt', N'Sử dụng bình thường'),
('P01', 'M02', '2021-04-25', NULL, N'Tốt', N'Sử dụng bình thường'),
('P03', 'M03', '2007-01-05', '2010-01-05', N'Tốt', N'Đang chạy'),
('P02', 'M04', '2022-05-15', NULL, N'Tốt', N'Sử dụng bình thường'),
('P02', 'M05', '2020-09-01', NULL, N'Tốt', N'Sử dụng bình thường');

-- 10. KHẤU HAO (Đảm bảo Câu 7 có ngày 1/5/2007 và Câu 10 có tỷ lệ > 0.9 sau 1 năm)
INSERT INTO KHAU_HAO (MA_MON, NGAY, TY_LE_KH) VALUES
('M03', '2007-05-01', 0.15), -- Khấu hao quạt trần Á Châu đúng ngày 1/5/2007 (Câu 7)
('M05', '2022-09-01', 0.95), -- Khấu hao Laptop ở Phòng NC&PT > 90% sau 1 năm (Câu 10)
('M01', '2023-12-31', 0.20),
('M02', '2023-12-31', 0.20);

-- 11. THANH LÝ (Câu 9 yêu cầu khoảng thời gian 1/11/2007 - 31/12/2007)
INSERT INTO THANH_LY (MA_MON, NGAY_GIO, TRI_GIA, DV_TIEN) VALUES
('M03', '2007-11-20 09:30:00', 200000, 'VND'), -- Thanh lý trong tháng 11/2007
('M01', '2007-12-15 14:00:00', 5000000, 'VND'); -- Thanh lý trong tháng 12/2007